<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    0 => [
        'entity_id' => '1',
        'entity_type_id' => '3',
        'attribute_set_id' => '0',
        'parent_id' => '0',
        'created_at' => '2013-01-14 11:12:53',
        'updated_at' => '2013-01-14 11:12:53',
        'path' => '1',
        'position' => '0',
        'level' => '0',
        'children_count' => '33',
        'name' => 'Root Catalog',
        'description' => null,
        'status' => null,
        'previousSiblingId' => null,
        'defaultLocale' => 'de-DE',
        'image' => null,
    ],

    1 => [
        'entity_id' => '2',
        'entity_type_id' => '3',
        'attribute_set_id' => '3',
        'parent_id' => '1',
        'created_at' => '2013-01-14 11:12:53',
        'updated_at' => '2013-05-16 00:43:57',
        'path' => '1/2',
        'position' => '1',
        'level' => '1',
        'children_count' => '27',
        'name' => 'Default Category',
        'description' => null,
        'status' => '1',
        'previousSiblingId' => null,
        'defaultLocale' => 'de-DE',
        'image' => null,
        'meta_title' => 'meta title',
        'meta_description' => 'metaDescription - Standard - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem',
        'meta_keywords' => 'metaKeywords - Standard - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem',
        'translations' => [
            '1' => [
                'name' => [
                    'attribute_id' => 100,
                    'value' => 'Hauptkategorie',
                ],
                'oneAttribute' => [
                    'attribute_id' => 200,
                    'value' => 'attributeValue',
                ],
                'meta_title' => [
                    'attribute_id' => 203,
                    'value' => 'meta title',
                ],
                'meta_keywords' => [
                    'attribute_id' => 201,
                    'value' => 'metaKeywords - Tanslation - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem',
                ],
                'meta_description' => [
                    'attribute_id' => 202,
                    'value' => 'metaDescription - Translation - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem',
                ],
            ],
        ],
    ],

    2 => [
        'entity_id' => '4',
        'entity_type_id' => '3',
        'attribute_set_id' => '3',
        'parent_id' => '2',
        'created_at' => '2013-01-25 11:43:31',
        'updated_at' => '2016-03-31 08:59:19',
        'path' => '1/2/4',
        'position' => '2',
        'level' => '2',
        'children_count' => '4',
        'name' => 'Women',
        'description' => null,
        'status' => '1',
        'previousSiblingId' => null,
        'defaultLocale' => 'de-DE',
        'image' => null,
    ],

    3 => [
        'entity_id' => '5',
        'entity_type_id' => '3',
        'attribute_set_id' => '3',
        'parent_id' => '2',
        'created_at' => '2013-01-25 11:44:47',
        'updated_at' => '2015-05-19 05:38:53',
        'path' => '1/2/5',
        'position' => '3',
        'level' => '2',
        'children_count' => '5',
        'name' => 'Men',
        'description' => null,
        'status' => '1',
        'previousSiblingId' => '4',
        'defaultLocale' => 'de-DE',
        'image' => null,
    ],

    4 => [
        'entity_id' => '6',
        'entity_type_id' => '3',
        'attribute_set_id' => '3',
        'parent_id' => '2',
        'created_at' => '2013-01-25 11:47:41',
        'updated_at' => '2015-05-19 05:38:59',
        'path' => '1/2/6',
        'position' => '4',
        'level' => '2',
        'children_count' => '4',
        'name' => 'Accessories',
        'description' => null,
        'status' => '1',
        'previousSiblingId' => '5',
        'defaultLocale' => 'de-DE',
        'image' => null,
    ],
];
