<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    0 => [
        'entity_id' => '402',
        'entity_type_id' => '4',
        'attribute_set_id' => '13',
        'type_id' => 'configurable',
        'sku' => 'msj000c',
        'has_options' => '1',
        'required_options' => '1',
        'created_at' => '2013-03-05 07:25:10',
        'updated_at' => '2013-03-20 17:58:34',
        'instock' => '0.0000',
        'stockmin' => '0.0000',
        'minpurchase' => '100.0000',
        'maxpurchase' => '0.0000',
        'parentId' => null,
        'allow_message' => null,
        'cost' => null,
        'country_of_manufacture' => null,
        'custom_design' => null,
        'custom_design_from' => null,
        'custom_design_to' => null,
        'custom_layout_update' => null,
        'description' => 'Button front. Long sleeves. Tapered collar, chest pocket, french cuffs.',
        'email_template' => null,
        'gallery' => null,
        'gift_message_available' => null,
        'gift_wrapping_available' => null,
        'gift_wrapping_price' => null,
        'group_price' => null,
        'image' => '/m/s/msj000t_2.jpg',
        'image_label' => null,
        'is_recurring' => null,
        'is_redeemable' => null,
        'lifetime' => null,
        'manufacturer' => null,
        'media_gallery' => null,
        'meta_description' => 'metaDescription - Standard - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore',
        'meta_keyword' => 'metaKeyword - Standard - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore',
        'meta_title' => 'metaTitle - Standard - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore',
        'minimal_price' => null,
        'msrp' => null,
        'msrp_display_actual_price_type' => '4',
        'msrp_enabled' => '2',
        'name' => 'French Cuff Cotton Twill Oxford',
        'news_from_date' => null,
        'news_to_date' => null,
        'old_id' => null,
        'open_amount_max' => null,
        'open_amount_min' => null,
        'options_container' => 'container1',
        'page_layout' => 'one_column',
        'price' => '190.0000',
        'price_view' => null,
        'recurring_profile' => null,
        'short_description' => 'Made with wrinkle resistant cotton twill, this French-cuffed luxury dress shirt is perfect for Business Class frequent flyers.',
        'small_image' => '/m/s/msj000t_2.jpg',
        'small_image_label' => null,
        'special_from_date' => null,
        'special_price' => null,
        'special_to_date' => null,
        'status' => '1',
        'tax_class_id' => '2',
        'thumbnail' => '/m/s/msj000t_2.jpg',
        'thumbnail_label' => null,
        'tier_price' => null,
        'url_key' => 'french-cuff-cotton-twill-oxford',
        'url_path' => 'french-cuff-cotton-twill-oxford-570.html',
        'use_config_allow_message' => null,
        'use_config_email_template' => null,
        'use_config_is_redeemable' => null,
        'use_config_lifetime' => null,
        'priceIsGross' => false,
        'translations' => [
            '1' => [
                'name' => [
                    'attribute_id' => 100,
                    'value' => 'EN - Produktübersetzung',
                ],
                'oneAttribute' => [
                    'attribute_id' => 200,
                    'value' => 'attributeValue',
                ],
                'meta_keyword' => [
                    'attribute_id' => 201,
                    'value' => 'metaKeyword - EN - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore',
                ],
                'meta_title' => [
                    'attribute_id' => 202,
                    'value' => 'metaTitle - EN - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore',
                ],
                'meta_description' => [
                    'attribute_id' => 203,
                    'value' => 'metaDescription - EN - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore',
                ],
            ],
        ],
        'visibility' => [
            0 => [
                'store_id' => '0',
                'value' => '1',
            ],
        ],
        'weight' => '1.5000',
        'attributes' => [
            0 => [
                'attribute_id' => '175',
                'attribute_code' => 'occasion',
                'value' => '30',
            ],
            1 => [
                'attribute_id' => '176',
                'attribute_code' => 'apparel_type',
                'value' => '41',
            ],
            2 => [
                'attribute_id' => '178',
                'attribute_code' => 'sleeve_length',
                'value' => '47',
            ],
            3 => [
                'attribute_id' => '179',
                'attribute_code' => 'fit',
                'value' => '51',
            ],
            4 => [
                'attribute_id' => '184',
                'attribute_code' => 'gender',
                'value' => '93',
            ],
        ],
        'categories' => [
            0 => [
                'productId' => '402',
                'categoryId' => '15',
            ],
        ],
        'media' => [
            0 => [
                'image' => '/m/s/msj000t_2.jpg',
                'description' => null,
                'position' => '1',
                'main' => '1',
            ],
            1 => [
                'image' => '/m/s/msj000a_2.jpg',
                'description' => null,
                'position' => '2',
                'main' => '0',
            ],
            2 => [
                'image' => '/m/s/msj000c_2.jpg',
                'description' => null,
                'position' => '4',
                'main' => '0',
            ],
        ],
        'configuratorSettings' => [
            0 => [
                'parentId' => '402',
                'groupId' => '92',
                'groupName' => 'color',
                'optionId' => '22',
                'optionValue' => 'White',
            ],
            1 => [
                'parentId' => '402',
                'groupId' => '180',
                'groupName' => 'size',
                'optionId' => '80',
                'optionValue' => 'S',
            ],
            2 => [
                'parentId' => '402',
                'groupId' => '180',
                'groupName' => 'size',
                'optionId' => '79',
                'optionValue' => 'M',
            ],
            3 => [
                'parentId' => '402',
                'groupId' => '180',
                'groupName' => 'size',
                'optionId' => '78',
                'optionValue' => 'L',
            ],
            4 => [
                'parentId' => '402',
                'groupId' => '180',
                'groupName' => 'size',
                'optionId' => '81',
                'optionValue' => 'XS',
            ],
            5 => [
                'parentId' => '402',
                'groupId' => '180',
                'groupName' => 'size',
                'optionId' => '77',
                'optionValue' => 'XL',
            ],
        ],
    ],
    1 => [
        'entity_id' => '498',
        'entity_type_id' => '4',
        'attribute_set_id' => '13',
        'type_id' => 'simple',
        'sku' => 'msj000xs',
        'has_options' => '0',
        'required_options' => '0',
        'created_at' => '2013-03-12 03:12:19',
        'updated_at' => '2014-03-08 09:53:09',
        'instock' => '8.0000',
        'stockmin' => '0.0000',
        'minpurchase' => '1.0000',
        'maxpurchase' => '0.0000',
        'parentId' => '402',
        'allow_message' => null,
        'cost' => null,
        'country_of_manufacture' => null,
        'custom_design' => null,
        'custom_design_from' => null,
        'custom_design_to' => null,
        'custom_layout_update' => null,
        'description' => 'Button front. Long sleeves. Tapered collar, chest pocket, french cuffs.',
        'email_template' => null,
        'gallery' => null,
        'gift_message_available' => null,
        'gift_wrapping_available' => null,
        'gift_wrapping_price' => null,
        'group_price' => null,
        'image' => '/m/s/msj000t_3.jpg',
        'image_label' => null,
        'is_recurring' => '0',
        'is_redeemable' => null,
        'lifetime' => null,
        'manufacturer' => null,
        'media_gallery' => null,
        'meta_description' => null,
        'meta_keyword' => null,
        'meta_title' => null,
        'minimal_price' => null,
        'msrp' => null,
        'msrp_display_actual_price_type' => '4',
        'msrp_enabled' => '2',
        'name' => 'French Cuff Cotton Twill Oxford',
        'news_from_date' => '2013-03-01 00:00:00',
        'news_to_date' => null,
        'old_id' => null,
        'open_amount_max' => null,
        'open_amount_min' => null,
        'options_container' => 'container1',
        'page_layout' => 'one_column',
        'price' => '190.0000',
        'price_view' => null,
        'recurring_profile' => null,
        'short_description' => 'Made with wrinkle resistant cotton twill, this French-cuffed luxury dress shirt is perfect for Business Class frequent flyers.',
        'small_image' => '/m/s/msj000t_3.jpg',
        'small_image_label' => null,
        'special_from_date' => null,
        'special_price' => null,
        'special_to_date' => null,
        'status' => '1',
        'tax_class_id' => '2',
        'thumbnail' => '/m/s/msj000t_3.jpg',
        'thumbnail_label' => null,
        'tier_price' => null,
        'url_key' => 'french-cuff-cotton-twill-oxford',
        'url_path' => 'french-cuff-cotton-twill-oxford-571.html',
        'use_config_allow_message' => null,
        'use_config_email_template' => null,
        'use_config_is_redeemable' => null,
        'use_config_lifetime' => null,
        'priceIsGross' => true,
        'visibility' => [
            0 => [
                'store_id' => '0',
                'value' => '1',
            ],
        ],
        'weight' => '1.0000',
        'attributes' => [
            0 => [
                'attribute_id' => '175',
                'attribute_code' => 'occasion',
                'value' => '30',
            ],
            1 => [
                'attribute_id' => '176',
                'attribute_code' => 'apparel_type',
                'value' => '41',
            ],
            2 => [
                'attribute_id' => '178',
                'attribute_code' => 'sleeve_length',
                'value' => '47',
            ],
            3 => [
                'attribute_id' => '179',
                'attribute_code' => 'fit',
                'value' => '51',
            ],
            4 => [
                'attribute_id' => '184',
                'attribute_code' => 'gender',
                'value' => '93',
            ],
        ],
        'media' => [
            0 => [
                'image' => '/m/s/msj000t_3.jpg',
                'description' => null,
                'position' => '1',
                'main' => '1',
            ],
        ],
    ],
];
