<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    0 => [
        'url_rewrite_id' => '1',
        'entity_type' => 'product',
        'entity_id' => '10',
        'request_path' => 'women/tops-women/jackets-women/adrienne-trek-jacket.html',
        'target_path' => 'catalog/product/view/id/1323/category/10',
        'redirect_type' => '0',
        'store_id' => '1',
        'description' => null,
        'is_autogenerated' => '1',
        'metadata' => '{"category_id":"17"}',
        'locale' => 'en-GB',
        'product_id' => '10',
        'category_id' => '17',
    ],

    1 => [
        'url_rewrite_id' => '2',
        'entity_type' => 'product',
        'entity_id' => '10',
        'request_path' => 'hyperion-elements-jacket.html',
        'target_path' => 'catalog/product/view/id/10',
        'redirect_type' => '0',
        'store_id' => '1',
        'description' => null,
        'is_autogenerated' => '1',
        'metadata' => null,
        'locale' => 'en-GB',
        'product_id' => '10',
    ],

    2 => [
        'url_rewrite_id' => '3',
        'entity_type' => 'category',
        'entity_id' => '17',
        'request_path' => 'men.html',
        'target_path' => 'catalog/category/view/id/17',
        'redirect_type' => '0',
        'store_id' => '1',
        'description' => null,
        'is_autogenerated' => '1',
        'metadata' => null,
        'locale' => 'en-GB',
        'category_id' => '17',
    ],
];
