name: Reusable PHPUnit

on:
  workflow_call:
    inputs:
      extension_name:
        required: true
        type: string
      platform_branch:
        required: false
        type: string
        default: trunk
      assistant_branch:
        required: false
        type: string
        default: ""

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        mysql_image: ["mysql:8.0", "mariadb:10.11"]
        php_version: ["8.2", "8.3"]
    steps:
      - name: Checkout SwagMigrationMagento
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: custom/plugins/${{ inputs.extension_name }}

      - name: Setup SwagMigrationMagento
        uses: ./custom/plugins/SwagMigrationMagento/.github/actions/setup-magento-plugin
        with:
          php-version: ${{ matrix.php_version }}
          mysql-version: ${{ matrix.mysql_image }}
          platform-branch: ${{ inputs.platform_branch }}
          assistant-branch: ${{ inputs.assistant_branch }}

      - name: Run PHPUnit
        working-directory: custom/plugins/${{ inputs.extension_name }}
        run: |
          composer dump-autoload --dev
          php -d pcov.enabled=1 -d pcov.directory=${PWD}/src -d pcov.exclude='~(vendor|tests|node_modules)~' ${GITHUB_WORKSPACE}/vendor/bin/phpunit --configuration phpunit.xml.dist
