name: Reusable PHPUnit

on:
  workflow_call:
    inputs:
      extension_name:
        required: true
        type: string
      platform_branch:
        required: false
        type: string
        default: trunk

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql_image: ["mysql:8.0", "mariadb:10.11"]
        php_version: ["8.2", "8.3"]
    steps:
      - name: Checkout SwagMigrationMagento
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.number && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
          path: custom/plugins/${{ inputs.extension_name }}

      - name: Setup SwagMigrationMagento
        uses: ./custom/plugins/SwagMigrationMagento/.github/actions/setup-magento-plugin
        with:
          php-version: ${{ matrix.php_version }}
          mysql-version: ${{ matrix.mysql_image }}
          extension-ref: ${{ github.event.pull_request.number && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
          platform-branch: ${{ inputs.platform_branch }}

      - name: Run PHPUnit
        working-directory: custom/plugins/${{ inputs.extension_name }}
        run: |
          composer dump-autoload --dev
          php -d pcov.enabled=1 -d pcov.directory=${PWD}/src -d pcov.exclude='~(vendor|tests|node_modules)~' ${GITHUB_WORKSPACE}/vendor/bin/phpunit --configuration phpunit.xml.dist
