name: Integration

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  danger:
    name: Danger Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Danger PHP
        uses: docker://ghcr.io/shyim/danger-php:latest
        with:
          args: ci
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}

  phpunit:
    name: PHPUnit Tests
    uses: ./.github/workflows/action-phpunit.yml
    with:
      extension_name: ${{ github.event.repository.name }}
      platform_branch: trunk
