name: PHP Checks

on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - composer.json
      - src/**/*.php
      - tests/**/*.php
  workflow_dispatch:

jobs:
  codestyle_php:
    name: Codestyle PHP
    runs-on: ubuntu-latest
    steps:
      - name: Run PHP CS Fixer
        uses: shopware/github-actions/cs-fixer@main
        with:
          rules: ""

  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SwagMigrationMagento
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ github.event.repository.name }}
      - name: Setup SwagMigrationMagento
        uses: ./custom/plugins/SwagMigrationMagento/.github/actions/setup-magento-plugin
        with:
          platform-branch: trunk
      - name: Run PHPStan
        run: |
          symfony composer -d custom/plugins/${{ github.event.repository.name }} dump-autoload --dev
          symfony composer -d custom/plugins/${{ github.event.repository.name }} run phpstan
