name: PHP Checks

on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - composer.json
      - src/**/*.php
      - tests/**/*.php
      - .github/workflows/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  codestyle_php:
    name: Codestyle PHP
    runs-on: ubuntu-latest
    steps:
      - name: Run PHP CS Fixer
        uses: shopware/github-actions/cs-fixer@main
        with:
          rules: ""

  phpstan:
    name: PHPStan Analysis
    uses: ./.github/workflows/action-phpstan.yml
    with:
      extension_name: ${{ github.event.repository.name }}
      platform_branch: trunk

  extension_verifier:
    name: Extension Verifier (${{ matrix.check-against }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check-against: [lowest, highest]
    steps:
      - name: Checkout SwagMigrationMagento
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Remove PHPStan config
        run: rm phpstan.neon.dist

      - name: Allow composer to resolve advisory-affected releases
        run: composer config policy.advisories.block false

      - name: Run verifier
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.check-against }}
